### ISSUE TITLE
Spaces between delimited file list in the ResultSqlFiles parameter causes file not found errors

### ISSUE THREAD

**Issue by klassenjr** [HexisData/hqTestLite#8]
Bad:
-ResultSqlFiles "verifyExceptionStage.sql, verifyInSstLotPreTyped.sql, verifyInSstLotRawStore.sql, verifyInSstLotTyped.sql, verifyInSstLotTypedStore.sql" `

Good:
-ResultSqlFiles "verifyExceptionStage.sql,verifyInSstLotPreTyped.sql,verifyInSstLotRawStore.sql,verifyInSstLotTyped.sql,verifyInSstLotTypedStore.sql" `

[ERROR] Invoke-Sqlcmd : Could not find file 
[ERROR] 'X:\Funds\Trunk\Testing\UnitTests\UnitTests\tests\load\SST\LOT\ 
[ERROR] verifyInSstLotPreTyped.sql'.
[ERROR] At X:\Funds\Trunk\Testing\UnitTests\UnitTests\framework\hqTestLite.psm1:47 
[ERROR] char:7
[ERROR] +                         Invoke-Sqlcmd -ServerInstance $DbServer -Database 
[ERROR] $DbName -InputFile $SqlP ...
[ERROR] +                         
[ERROR] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]     + CategoryInfo          : InvalidResult: (WST-STSQ-000488:PSObject) [Invok 
[ERROR]    e-Sqlcmd], FileNotFoundException
[ERROR]     + FullyQualifiedErrorId : ExecutionFailed,Microsoft.SqlServer.Management.P 
[ERROR]    owerShell.GetScriptCommand

**Comment by aroder** [comment]
Looks like we need to trim the CSV values. I watched Jim remove the spaces, and the test then ran without error

**Comment by jscroft** [comment]
Estimate: 2 hrs
